version: '3.9'
services:
  backend:
    build: 
      context: ./
      target: dev
    volumes:
      - .:/src
    command: yarn start
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*